#!/usr/bin/python3

from fitparse_to_gpxpy import *
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="convert Garmin FIT files to GPX tracks")

    parser.add_argument("fitfile", help="fit file to read")
    parser.add_argument("-o", "--output", help="specify target file")
    parser.add_argument("-c", "--stdout", action="store_true", help="print GPX/XML to stdout")

    args = parser.parse_args()

    gpx = parse_fit_to_gpx(args.fitfile)

    if args.output:
        output_file = open(args.output, 'x')
        output_file.write(gpx.to_xml())

        output_file.close()

    elif args.stdout:
        print(gpx.to_xml())

    else:
        # omit ending *.fit and append .gpx instead
        if args.fitfile[-4:].lower() == ".fit":
            output_filename = args.fitfile[:-4] + ".gpx"
        else:
            output_filename = args.fitfile + ".gpx"

        output_file = open(output_filename, 'x')
        output_file.write(gpx.to_xml())

        output_file.close()
